server:
  port: 9000
  servlet:
    context-path: /api/v1

security-service: ${SECURITY_SERVICE_URL:http://localhost:9010}

spring:
  application:
    name: card-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-request
              uri: ${AUTH_REQUEST_ROUTE_URI:http://localhost:9001}
              predicates:
                - Path=/api/v1/payment/authorize
              filters:
                - name: CardValidation
                - name: JwtInjection
                  args:
                    isLogIP: true

logging:
  level:
    org.springframework: INFO
    com.howwow: INFO
