services:
  h2-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: h2-keys-db
    ports:
      - "9092:9092"    # TCP сервер H2
      - "81:81"    # Веб-консоль H2
    environment:
      H2_USER: sa
      H2_PASSWORD: n4D#xQ8vTpZ3
      H2_TCP_ALLOW_OTHERS: "true"
    networks:
      - backend-network

  cpp-security-service:
    build:
      context: .
      dockerfile: cpp-security-service/Dockerfile
    container_name: cpp-security-service
    ports:
      - "9010:9010"
    depends_on:
      - h2-db
    environment:
      SPRING_PROFILES_ACTIVE: default
    networks:
      - backend-network

  cpp-card-gateway:
    build:
      context: .
      dockerfile: cpp-card-gateway/Dockerfile
    container_name: cpp-card-gateway
    ports:
      - "9000:9000"
    depends_on:
      - h2-db
    env_file:
      - cpp-card-gateway/.env
    environment:
      SPRING_PROFILES_ACTIVE: default
    networks:
      - backend-network

  cpp-auth-request:
    build:
      context: .
      dockerfile: cpp-auth-request/Dockerfile
    container_name: cpp-auth-request
    ports:
      - "9001:9001"
    depends_on:
      - h2-db
    env_file:
      - cpp-auth-request/.env
    environment:
      SPRING_PROFILES_ACTIVE: default
    networks:
      - backend-network

  cpp-logging-service:
    build:
      context: .
      dockerfile: cpp-logging-service/Dockerfile
    container_name: cpp-logging-service
    env_file:
      - .env
    ports:
      - "9020:9020"
    depends_on:
      - cpp-logging-database
    environment:
      SPRING_PROFILES_ACTIVE: default
    networks:
      - backend-network

  cpp-logging-liquibase:
    image: liquibase/liquibase:4.32.0
    depends_on:
      cpp-logging-database:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_URL: ${CPP_LOGGING_SERVICE_DATASOURCE_URL}
      LIQUIBASE_COMMAND_USERNAME: ${CPP_LOGGING_SERVICE_DATASOURCE_USERNAME}
      LIQUIBASE_COMMAND_PASSWORD: ${CPP_LOGGING_SERVICE_DATASOURCE_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./cpp-logging-service/src/main/resources/db/changelog:/liquibase/changelog
    command:
      - --searchPath=/liquibase/changelog
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - update
    networks:
      - backend-network
    restart: "no"

  cpp-logging-database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${CPP_LOGGING_SERVICE_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${CPP_LOGGING_SERVICE_DATASOURCE_PASSWORD}
      POSTGRES_DB: cpp_logging_db
      POSTGRES_MULTIPLE_DATABASES: cpp_logging_db
    env_file:
      - .env
    volumes:
      - log_data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CPP_LOGGING_SERVICE_DATASOURCE_USERNAME} -d cpp_logging_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
  cpp-notification-service:
    build:
      context: .
      dockerfile: cpp-notification-service/Dockerfile
    container_name: cpp-notification-service
    env_file:
      - .env
    ports:
      - "9030:9030"
    depends_on:
      - cpp-notification-database
    environment:
      SPRING_PROFILES_ACTIVE: default
    networks:
      - backend-network
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
volumes:
  log_data: