server:
  port: ${CPP_BANK_GATEWAY_SERVICE_PORT}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: cpp-bank-gateway-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

keydb:
  datasource:
    url: ${KEY_DB_URL}
    username: ${KEY_DB_USERNAME}
    password: ${KEY_DB_PASSWORD}
    card-name: ${CARD_NAME_KEY}
    jwt-name: ${JWT_NAME_KEY}

logging:
  level:
    org.springframework: INFO
    com.howwow: INFO
