server:
  port: ${CPP_PAYMENT_ORCHESTRATOR_SERVICE_PORT}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: cpp-payment-orchestrator-service
  task:
    execution:
      pool:
        core-size: 3
        max-size: 10
        queue-capacity: 1000

bank-gateway:
  service:
    url: ${CPP_BANK_GATEWAY_SERVICE_URI}

payment-processor:
  service:
    url: ${CPP_PAYMENT_PROCESSOR_SERVICE_URI}

logging-service:
  service:
    url: ${CPP_LOGGING_SERVICE_URI}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

keydb:
  datasource:
    url: ${KEY_DB_URL}
    username: ${KEY_DB_USERNAME}
    password: ${KEY_DB_PASSWORD}
    card-name: ${CARD_NAME_KEY}
    jwt-name: ${JWT_NAME_KEY}

logging:
  level:
    org.springframework: INFO
    com.howwow: INFO
