spring:
  application:
    name: cpp-notification-service
  task:
    execution:
      pool:
        core-size: 3
        max-size: 10
        queue-capacity: 1000
  kafka:
    consumer:
      group-id: payment-consumers-email
      enable-auto-commit: false
      auto-offset-reset: earliest
      isolation-level: read_committed
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: ${CPP_NOTIFICATION_SERVICE_KAFKA_BOOTSTRAP_SERVERS}
      properties:
        spring.json.trusted.packages: "com.howwow.**"
    listener:
      ack-mode: manual
  mail:
    host: ${CPP_NOTIFICATION_SERVICE_MAIL_HOST}
    port: ${CPP_NOTIFICATION_SERVICE_MAIL_PORT}
    username: ${CPP_NOTIFICATION_SERVICE_MAIL_USERNAME}
    password: ${CPP_NOTIFICATION_SERVICE_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: ${CPP_NOTIFICATION_SERVICE_PORT}
  servlet:
    context-path: /api/v1

logging:
  level:
    org.springframework: INFO
    com.howwow: INFO