server:
  port: 9001
  servlet:
    context-path: /api/v1

spring:
  application:
    name: auth-request-service

bank-gateway:
  service:
    url: ${BANK_GATEWAY_SERVICE_URL:http://localhost:9003}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

keydb:
  datasource:
    url: jdbc:h2:tcp://h2-db:9092/./keysdb
    username: sa
    password: n4D#xQ8vTpZ3

logging:
  level:
    org.springframework: INFO
    com.howwow: INFO
