spring:
  application:
    name: cpp-payment-processor-service
  kafka:
    bootstrap-servers: ${CPP_PAYMENT_PROCESSOR_SERVICE_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        enable.idempotence: true
  data:
    redis:
      host: ${CPP_PAYMENT_PROCESSOR_SERVICE_REDIS_HOST}
      port: ${CPP_PAYMENT_PROCESSOR_SERVICE_REDIS_PORT}
server:
  port: ${CPP_PAYMENT_PROCESSOR_SERVICE_PORT}
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    org.springframework: INFO
    com.howwow: INFO
    org.apache.kafka: INFO
