server:
  port: ${CPP_PAYMENT_GATEWAY_SERVICE_PORT}
  servlet:
    context-path: /api/v1

security-service: ${CPP_SECURITY_SERVICE_URI}

spring:
  application:
    name: cpp-payment-gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: cpp-payment-orchestrator-service
              uri: ${CPP_PAYMENT_ORCHESTRATOR_SERVICE_URI}
              predicates:
                - Path=/api/v1/payment/authorize
              filters:
                - name: CardValidation
                - name: JwtInjection
            - id: cpp-logging-service-api
              uri: ${CPP_LOGGING_SERVICE_URI}
              predicates:
                - Path=/api/v1/logging/fetch-logs
            - id: cpp-payment-recording-service-api
              uri: ${CPP_PAYMENT_RECORDING_SERVICE_URI}
              predicates:
                - Path=/api/v1/payment/**
logging:
  level:
    org.springframework: INFO
    com.howwow: INFO
