spring:
  application:
    name: cpp-payment-recording-service
  kafka:
    consumer:
      group-id: payment-consumers-recording
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.howwow.**"
      bootstrap-servers: ${CPP_PAYMENT_RECORDING_SERVICE_KAFKA_BOOTSTRAP_SERVERS}
    listener:
      ack-mode: manual
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: cpp_payment_schema
    open-in-view: false
  datasource:
    url: ${CPP_PAYMENT_RECORDING_SERVICE_DATASOURCE_URL}
    username: ${CPP_PAYMENT_RECORDING_SERVICE_DATASOURCE_USERNAME}
    password: ${CPP_PAYMENT_RECORDING_SERVICE_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

server:
  port: ${CPP_PAYMENT_RECORDING_SERVICE_PORT}
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    org.springframework: INFO
    com.howwow: INFO
    org.apache.kafka: INFO

