spring:
  application:
    name: cpp-security-service

jwt:
  expirationTime: 600

server:
  port: ${SECURITY_SERVICE_PORT:9010}
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

keydb:
  datasource:
    url: jdbc:h2:tcp://h2-db:9092/./keysdb
    username: sa
    password: n4D#xQ8vTpZ3
    card-name: card_key
    jwt-name: jwt_signing_key

logging:
  level:
    org.springframework: INFO
    com.howwow: INFO
