spring:
  application:
    name: cpp-logging-service
  datasource:
    url: ${CPP_LOGGING_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cpp_logging_db}
    username: ${CPP_LOGGING_SERVICE_DATASOURCE_USERNAME:postgres}
    password: ${CPP_LOGGING_SERVICE_DATASOURCE_PASSWORD:sa}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: cpp_logging_schema

  liquibase:
    enabled: false

server:
  port: ${CPP_LOGGING_SERVICE_PORT:9020}
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    org.springframework: INFO
    com.howwow: INFO